site_name: OE1WFM
site_author: Martin Weise
copyright: CC BY 4.0 Martin Weise
extra:
  homepage: https://oe1wfm.at
  generator: false
nav:
  - Home: 'index.md'
  - Operation: 'operation.md'
  - Hardware: 'hardware.md'
  - Software: 'software.md'
  - Contact: 'contact.md'
extra_css:
  - stylesheets/extra.css
theme:
  language: en
  favicon: images/favicon.svg
  font:
    text: IBM Plex Serif
    code: IBM Plex Mono
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.annotate
  palette:
    - scheme: default
      primary: teal
      font:
        code: Roboto Mono
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      font:
        code: Roboto Mono
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  name: material
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - footnotes
