site_name: OE1WFM
site_author: Martin Weise
copyright: CC BY 4.0 Martin Weise
extra:
  homepage: https://oe1wfm.at
nav:
  - Home: 'index.md'
  - Contact: 'contact.md'
extra_css:
  - stylesheets/extra.css
theme:
  language: en
  font:
    text: IBM Plex Serif
    code: IBM Plex Mono
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.annotate
  palette:
    - scheme: default
      primary: blue grey
      font:
        code: Roboto Mono
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - scheme: slate
      primary: black
      font:
        code: Roboto Mono
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
  name: material
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences